# Generated by Django 3.2 on 2021-05-22 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airline', '0002_auto_20210522_0220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flight',
            name='destination',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='flight',
            name='origin',
            field=models.CharField(max_length=64),
        ),
        migrations.DeleteModel(
            name='Airport',
        ),
    ]
